export const TOGGLE_PROFILE = 'TOGGLE_PROFILE';
export const TOGGLE_PROJECTS = 'TOGGLE_PROJECTS';
export const TOGGLE_MESSAGE_TOAST = 'TOGGLE_MESSAGE_TOAST';
export const DISPLAY_TECH = 'DISPLAY_TECH';
export const THANKS_TOAST = 'THANKS_TOAST';
export const IS_LOADING = 'IS_LOADING';
export const SEND_MESSAGE = 'SEND_MESSAGE';

export const MESSAGE_ERROR = 'MESSAGE_ERROR';
export const FORM_NAME_ERROR = 'FORM_NAME_ERROR';
export const FORM_EMAIL_ERROR = 'FORM_EMAIL_ERROR';
export const FORM_TEXT_ERROR = 'FORM_TEXT_ERROR';
export const ERROR_TOAST = 'ERROR_TOAST';
