export const TOGGLE_PROFILE = 'TOGGLE_PROFILE';
export const TOGGLE_PROJECTS = 'TOGGLE_PROJECTS';
export const TOGGLE_MESSAGE_TOAST = 'TOGGLE_MESSAGE_TOAST';
export const DISPLAY_TECH = 'DISPLAY_TECH';
